version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_TEST_ALL_6AUGProject
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_test_all_6aug.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_TEST_ALL_6AUGProject
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: project.siqa_test_all_6aug.integrations:deepclonetest
  packages:
  - name: SIQA_TEST_ALL_6AUGProject
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
